# Generated by Django 4.2.27 on 2026-01-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '__first__'),
        ('supermarches', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(choices=[('KG', 'Kilogramme'), ('UNITE', 'Unité'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('GRAMME', 'Gramme')], default='UNITE', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('preparation_time', models.PositiveIntegerField(blank=True, help_text='Minutes', null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.restaurant')),
                ('supermarche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supermarches.supermarche')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
