# Generated by Django 4.2.27 on 2026-01-01 14:57

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Catégories Restaurant',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rccm_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurant_license', models.CharField(blank=True, max_length=100, null=True)),
                ('cuisine_type', models.CharField(choices=[('AFRICAIN', 'Africain'), ('ASIATIQUE', 'Asiatique'), ('EUROPEEN', 'Européen'), ('FAST_FOOD', 'Fast Food'), ('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('SUSHI', 'Sushi'), ('ITALIEN', 'Italien'), ('FRANCAIS', 'Français'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/')),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('full_address', models.TextField()),
                ('delivery_radius_km', models.PositiveIntegerField(default=5)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('avg_preparation_time', models.PositiveIntegerField(default=30, help_text='Minutes')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('price_level', models.CharField(choices=[('€', 'Budget'), ('€€', 'Moyen'), ('€€€', 'Cher')], default='€€', max_length=5)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_account', models.JSONField(blank=True, default=dict)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('is_open', models.BooleanField(default=True, help_text='Currently open')),
                ('is_active', models.BooleanField(default=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'RESTAURANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
