# Generated by Django 4.2.29 on 2026-03-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_commande_livreur_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='campay_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CamPay Référence'),
        ),
        migrations.AddField(
            model_name='commande',
            name='operator',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Opérateur (MTN/ORANGE)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de paiement'),
        ),
    ]
