# Generated by Django 4.2 on 2026-03-08

from django.db import migrations, models


def fill_client_name(apps, schema_editor):
    Commande = apps.get_model('orders', 'Commande')
    for commande in Commande.objects.select_related('client').all():
        if commande.client_name:
            continue
        client = commande.client
        if client is None:
            continue
        full_name = f"{(client.first_name or '').strip()} {(client.last_name or '').strip()}".strip()
        commande.client_name = full_name or getattr(client, 'email', '') or ''
        commande.save(update_fields=['client_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_commande_campay_reference_commande_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='commande',
            name='delivery_preference',
            field=models.CharField(choices=[('DES_QUE_PRETE', 'Dès que prête'), ('PLANIFIEE', 'Planifiée')], default='DES_QUE_PRETE', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='requested_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(fill_client_name, migrations.RunPython.noop),
    ]
