# Generated by Django 4.2 on 2026-03-08

from django.db import migrations, models


def fill_client_phone_and_address(apps, schema_editor):
    Commande = apps.get_model('orders', 'Commande')
    for commande in Commande.objects.select_related('client').all():
        update_fields = []

        if not commande.client_phone and commande.client_id:
            phone = (getattr(commande.client, 'phone', '') or '').strip()
            if phone:
                commande.client_phone = phone
                update_fields.append('client_phone')

        if not commande.client_delivery_address:
            commande.client_delivery_address = commande.delivery_address_text or ''
            update_fields.append('client_delivery_address')

        if update_fields:
            commande.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_commande_client_snapshot_and_delivery_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(fill_client_phone_and_address, migrations.RunPython.noop),
    ]
