# Generated by Django 4.2.27 on 2026-01-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('TEXTE', 'Texte'), ('NOMBRE', 'Nombre'), ('BOOLEAN', 'Booléen'), ('JSON', 'JSON')], default='TEXTE', max_length=20)),
                ('is_editable', models.BooleanField(default=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Paramètres Vérification',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='VerificationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
