# Generated by Django 4.2.27 on 2026-01-01 14:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
        ('livreurs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('city', models.CharField(max_length=100)),
                ('neighborhoods', models.JSONField(blank=True, default=list)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_fee_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_delivery_time', models.PositiveIntegerField(default=30, help_text='Minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrajetLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trajet', to='orders.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='livreurs.livreur')),
            ],
            options={
                'ordering': ['-date_start'],
            },
        ),
    ]
