# Generated by Django 4.2.27 on 2026-01-02 13:38

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(choices=[('CLIENT', 'Client'), ('LIVREUR', 'Livreur'), ('RESTAURANT', 'Restaurant'), ('SUPERMARCHE', 'Supermarché'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('statut_verification', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS_VERIFICATION', 'En cours de vérification'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE', max_length=30)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=500, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('admin_verificateur', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PIECE_IDENTITE', "Pièce d'identité"), ('PERMIS_CONDUIRE', 'Permis de conduire'), ('CARTE_GRISE', 'Carte grise'), ('REGISTRE_COMMERCE', 'Registre de commerce'), ('LICENCE_RESTAURANT', 'Licence restaurant'), ('AUTORISATION_SANITAIRE', 'Autorisation sanitaire'), ('PHOTO_ETABLISSEMENT', 'Photo établissement'), ('CONTRAT', 'Contrat'), ('ASSURANCE', 'Assurance'), ('CERTIFICAT_DOMICILIATION', 'Certificat de domiciliation'), ('CASIER_JUDICIAIRE', 'Casier judiciaire'), ('ATTESTATION_DOMICILE', 'Attestation de domicile'), ('CERTIFICAT_MEDICAL', 'Certificat médical'), ('PHOTO_VEHICULE', 'Photo véhicule'), ('AUTRE', 'Autre')], max_length=50)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('EXPIRE', 'Expiré'), ('RENOUVELLEMENT_REQUIS', 'Renouvellement requis')], default='EN_ATTENTE', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('admin_verificateur', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-date_upload'],
                'unique_together': {('user', 'document_type', 'date_upload')},
            },
        ),
        migrations.CreateModel(
            name='NotificationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DOCUMENTS_REQUIS', 'Documents requis'), ('DOCUMENTS_RECUS', 'Documents reçus'), ('EN_VERIFICATION', 'En vérification'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('DOCUMENTS_MANQUANTS', 'Documents manquants'), ('DOCUMENT_EXPIRE', 'Document expiré'), ('RENOUVELLEMENT_REQUIS', 'Renouvellement requis')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('required_actions', models.JSONField(blank=True, default=list)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('documents', models.ManyToManyField(blank=True, to='users.documentverification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SOUMISSION_INITIALE', 'Soumission initiale'), ('DOCUMENTS_AJOUTES', 'Documents ajoutés'), ('EN_VERIFICATION', 'En vérification'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('SUSPENSION', 'Suspension'), ('REACTIVATION', 'Réactivation'), ('DEMANDE_INFO_SUPPLEMENTAIRE', "Demande d'info supplémentaire"), ('RENOUVELLEMENT_REQUIS', 'Renouvellement requis')], max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('documents', models.ManyToManyField(blank=True, to='users.documentverification')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='CriteresVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('LIVREUR', 'Livreur'), ('RESTAURANT', 'Restaurant'), ('SUPERMARCHE', 'Supermarché')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('verification_order', models.PositiveIntegerField(default=0)),
                ('verification_checklist', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('required_documents', models.ManyToManyField(blank=True, to='users.documentverification')),
            ],
            options={
                'ordering': ['verification_order'],
                'unique_together': {('user_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Maison, Bureau, etc.', max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Cameroun', max_length=100)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_main', '-date_creation'],
                'unique_together': {('user', 'is_main')},
            },
        ),
    ]
