# Generated by Django 4.2.27 on 2026-01-01 14:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('MOTO', 'Moto'), ('VOITURE', 'Voiture'), ('VELO', 'Vélo'), ('SCOOTER', 'Scooter')], max_length=20)),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('vehicle_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('driver_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_license_expiry', models.DateField(blank=True, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('current_position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('HORS_LIGNE', 'Hors ligne'), ('EN_LIGNE', 'En ligne'), ('EN_LIVRAISON', 'En livraison'), ('EN_PAUSE', 'En pause')], default='HORS_LIGNE', max_length=20)),
                ('action_radius_km', models.PositiveIntegerField(default=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('delivery_count', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_position_update', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.JSONField(blank=True, default=dict)),
                ('commission_type', models.CharField(choices=[('PERCENTAGE', 'Pourcentage'), ('FIXED', 'Montant fixe')], default='PERCENTAGE', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'LIVREUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='livreur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='StatistiquesLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('deliveries_today', models.PositiveIntegerField(default=0)),
                ('deliveries_week', models.PositiveIntegerField(default=0)),
                ('deliveries_month', models.PositiveIntegerField(default=0)),
                ('earnings_today', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earnings_week', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earnings_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_today_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_week_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_month_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_time_minutes', models.PositiveIntegerField(default=0)),
                ('average_rating_period', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('livreur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='livreurs.livreur')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
