# Generated by Django 4.2.27 on 2026-01-01 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NOUVELLE_COMMANDE', 'Nouvelle commande'), ('COMMANDE_ACCEPTEE', 'Commande acceptée'), ('LIVREUR_ASSIGNE', 'Livreur assigné'), ('EN_ROUTE', 'En route'), ('LIVREE', 'Livrée'), ('PROMOTION', 'Promotion'), ('VERIFICATION', 'Vérification'), ('ALERTE_DOCUMENT', 'Alerte document')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
